### ISSUE TITLE
Idea: Make gridlist scrolling speed a config setting

### ISSUE THREAD

**Issue by Zangomangu** [OvileAmriam/MTA-Beautify-Library#21]
The speed of the animation when accelerating/decelerating scrolling

**Comment by Zangomangu** [comment]
Also the slider animation speed when dragging it

**Comment by ov-aviril** [comment]
> The speed of the animation when accelerating/decelerating scrolling

Right now scrolling is based on number of streaks you do using mouse-wheel which gets faster every time you make more streaks on, for gridlist scroll amount is determined by `the row height x number of streaks` and talking about the animation speed of the scroller that can be made as a config (Global scroll speed, will apply to deckpane etc and every other component/elements wherever its applied; What do you think of this?)

**Comment by ov-aviril** [comment]
> The speed of the animation when accelerating/decelerating scrolling

- Added `animAcceleration` + `scrollAcceleration` template config for scrollbar component. [Example Template](https://github.com/OvileAmriam/MTA-Beautify-Library/blob/master/%5BExample%5D/beautify_example/configurations/templates/scrollbar.lua)
![image](https://user-images.githubusercontent.com/89867985/133131882-59f4f4af-5ffa-448d-8fdf-5cf0713ae3b8.png)

━━━━━━━━━━━━━━━━━━━━━━━━

> Also the slider animation speed when dragging it

- Added `slideAcceleration` template config for slider element (Will be integrated w/ dragger when its done). [Example Template](https://github.com/OvileAmriam/MTA-Beautify-Library/blob/master/%5BExample%5D/beautify_example/configurations/templates/slider.lua)
![image](https://user-images.githubusercontent.com/89867985/133132296-1bd7f68f-a65d-4112-a4f7-f0aa926a2c7e.png)
