### ISSUE TITLE
Idea: Give buttons a border or different background

### ISSUE THREAD

**Issue by Zangomangu** [OvileAmriam/MTA-Beautify-Library#23]
![image](https://user-images.githubusercontent.com/59518113/132546485-4f324b26-926d-46e5-995d-2e6b88ee370c.png)

I'm guessing this is just in the dev example, but they should probably have a border or more contrasted background?

**Comment by ov-aviril** [comment]
> ![image](https://user-images.githubusercontent.com/59518113/132546485-4f324b26-926d-46e5-995d-2e6b88ee370c.png)
> 
> I'm guessing this is just in the dev example, but they should probably have a border or more contrasted background?

![image](https://user-images.githubusercontent.com/89867985/133100703-61d6728a-9fac-41eb-bd74-31b758a22e24.png)
Solved & Updated git, check the latest template configs.
